import React, { Component } from 'react';
import { Text, View, TouchableOpacity, Image, ImageBackground } from 'react-native';
import { Icon, ListItem } from 'react-native-elements';


const list_annex = [
    {
        id: 'some ID generated by Firebase',
        name: 'PC Building',
        avatar_url: 'https://via.placeholder.com/128',
        status: 'Spaces Available',
        building: 'Main Building',
        room: 'Turrialba',
        day: 'Monday',
        start_date: 'April 22',
        end_date: 'July 22',
        instructor: 'Juan Monge',
        reason:  '',
        screen: 'BarraHonda'
      },
      {
        id: 'some ID generated by Firebase',
        name: 'PC Building',
        avatar_url: 'https://via.placeholder.com/128',
        status: 'Full',
        building: 'Annex Building',
        room: 'Barra Honda',
        day: 'Friday',
        start_date: 'April 22',
        end_date: 'July 22',
        instructor: 'Allan Valverde',
        reason:  '',
        screen: 'BarraHonda'
      },
      {
        id: 'some ID generated by Firebase',
        name: 'PC Building',
        avatar_url: 'https://via.placeholder.com/128',
        status: 'Spaces Available',
        building: 'Annex Building',
        room: 'Palo Verde',
        day: 'Saturday',
        start_date: 'April 22',
        end_date: 'July 22',
        instructor: 'Gabriel Montoya',
        reason:  '',
        screen: 'BarraHonda'
      },

      {
        id: 'some ID generated by Firebase',
        name: 'SOHO',
        avatar_url: 'https://via.placeholder.com/128',
        status: 'Full',
        building: 'Annex Building',
        room: 'Savegre',
        day: 'Thursday',
        start_date: 'April 22',
        end_date: 'July 22',
        instructor: 'Carlos Chinchilla',
        reason:  '',
        screen: 'BarraHonda'
      },
      {
        id: 'some ID generated by Firebase',
        name: 'SOHO',
        avatar_url: 'https://via.placeholder.com/128',
        status: 'Spaces Available',
        building: 'Annex Building',
        room: 'Chirripo',
        day: 'Monday',
        start_date: 'April 22',
        end_date: 'July 22',
        instructor: 'Sindy Campos',
        reason:  '',
        screen: 'BarraHonda'
      },




   // more items
]

export default class Groups extends Component {
    render() {
      return (
        <View style={{ flex: 1,backgroundColor: 'white'}}>
          {/*<TouchableOpacity style={{ margin:10, borderRadius:5}}>
            <ImageBackground 
              source={{ uri: 'https://via.placeholder.com/250x250' }} 
              style= {{ width: '100%', height: 60}}
              imageStyle={{ borderRadius:5 }}>
              <Text style={{ marginTop: 5 , textAlign:'center' }}> AAAAAA </Text>
            </ImageBackground>
      </TouchableOpacity>*/}

        {   
            list_annex.map((l, i) => (
              //console.warn(l.status + ' - ' + l.user + ': ' + l.reason),
              <ListItem
                key={i}
                leftAvatar={{ 
                    source: { 
                        uri: l.avatar_url }, 
                        showEditButton: true, 
                        editButton: { 
                            name: 'checkbox-blank-circle', 
                            type: 'material-community', 
                            color: (l.status.indexOf('Spaces Available')  ? '#FF0000' : '#008000'), 
                            underlayColor: '#000', size: 8 } }}
                title={l.name}
                subtitle={l.status}
                subtitleStyle={{ fontSize: 10}}
                rightSubtitle={ l.building + '\n' + l.day + '\n' + l.start_date + ' - ' + l.end_date + '\n' + l.instructor }
                rightSubtitleStyle={{ fontSize: 9 ,textAlign: "right" }}
                rightIcon={<Icon name='keyboard-arrow-right' color='grey' />}
                onPress={()=>this.props.navigation.navigate('GroupInfo')}
              />
            ))
          } 

          
        </View>
      );
    }
  }